version: '2.1'

services:

  elasticsearch:
    build: ./elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build: ./logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    container_name: logstash
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: ./kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    container_name: kibana
    networks:
      - elk
    depends_on:
      - elasticsearch
 
  filebeat:
    build: ./filebeat/
    container_name: filebeat
    networks:
      - elk
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  
    depends_on:
      - elasticsearch 
    # network_mode: host

  metricbeat:
    build: ./metricbeat/
    container_name: metricbeat
    networks: 
      - elk
    depends_on:
      - elasticsearch 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro

  elastalert:
    build: ./elastalert
    ports:
      - "3030:3030"
      - "3333:3333"
    container_name: elastalert
    networks:
      - elk
    depends_on:
      - elasticsearch 
    volumes:
      - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./elastalert/config/elastalert-test.yaml:/opt/elastalert/config-test.yaml
      - ./elastalert/config/config.json:/opt/elastalert-server/config/config.json
      - ./elastalert/rules:/opt/elastalert/rules
      - /opt/elastalert/smtp_auth_file.yml:/opt/elastalert/smtp_auth_file.yml
      - ./elastalert/rule_templates:/opt/elastalert/rule_templates 
     # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      #- /var/run/docker.sock:/var/run/docker.sock:ro 
    healthcheck:
        test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
        interval: 30s
        timeout: 10s
        retries: 5

networks:
  elk:
    driver: bridge
  
